/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1     */
/*  Created On : 06-дек-2024 17:36:32         */
/*  DBMS       : PostgreSQL             */
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seq_container_id;
DROP SEQUENCE IF EXISTS seq_interface_id;
DROP SEQUENCE IF EXISTS seq_operation_id;
DROP SEQUENCE IF EXISTS seq_parameter_id;
DROP SEQUENCE IF EXISTS seq_sla_id;

/* Drop Tables */

DROP TABLE IF EXISTS containers_interface CASCADE;
DROP TABLE IF EXISTS containers_product CASCADE;
DROP TABLE IF EXISTS interface CASCADE;
DROP TABLE IF EXISTS operation CASCADE;
DROP TABLE IF EXISTS parameter CASCADE;
DROP TABLE IF EXISTS realization_type CASCADE;
DROP TABLE IF EXISTS sla CASCADE;
DROP TABLE IF EXISTS status_interface CASCADE;

/* Create Sequences */

CREATE SEQUENCE seq_container_id INCREMENT 1 START 1;
CREATE SEQUENCE seq_interface_id INCREMENT 1 START 1;
CREATE SEQUENCE seq_operation_id INCREMENT 1 START 1;
CREATE SEQUENCE seq_parameter_id INCREMENT 1 START 1;
CREATE SEQUENCE seq_sla_id INCREMENT 1 START 1;

/* Create Tables */

CREATE TABLE containers_product
(
    id integer NOT NULL DEFAULT NEXTVAL('seq_container_id'::regclass),
    name varchar(80) NOT NULL,
    product_id integer NULL,
    code varchar(80) NULL,
    version varchar(50) NULL,
    created_date timestamp without time zone NULL,
    updated_date timestamp without time zone NULL,
    deleted_date timestamp without time zone NULL
);

CREATE TABLE interface
(
    id integer NOT NULL DEFAULT NEXTVAL('seq_interface_id'::regclass),
    name varchar(150) NULL,
    code varchar(50) NULL,
    spec_link varchar(150) NULL,
    version varchar(50) NULL,
    type_id integer NULL,
    description varchar(250) NULL,
    protocol varchar(50) NULL,
    status_id integer NULL,
    tc_id integer NULL,
    container_id integer NULL,
    created_date timestamp without time zone NULL,
    deleted_date timestamp without time zone NULL,
    updated_date timestamp without time zone NULL
);

CREATE TABLE operation
(
    id integer NOT NULL DEFAULT NEXTVAL('seq_operation_id'::regclass),
    interface_id integer NULL,
    name varchar(50) NULL,
    description varchar(250) NULL,
    type varchar(50) NULL,
    return_type varchar(100) NULL,
    created_date timestamp without time zone NULL,
    updated_date timestamp without time zone NULL,
    delete_date timestamp without time zone NULL
);

CREATE TABLE parameter
(
    id integer NOT NULL DEFAULT NEXTVAL('seq_parameter_id'::regclass),
    operation_id integer NULL,
    parameter_name varchar(100) NULL,
    parameter_type varchar(50) NULL,
    created_date timestamp without time zone NULL,
    deleted_date timestamp without time zone NULL
);

CREATE TABLE realization_type
(
    id integer NOT NULL,
    type varchar(80) NOT NULL
);

CREATE TABLE sla
(
    id integer NOT NULL DEFAULT NEXTVAL('seq_sla_id'::regclass),
    operation_id integer NULL,
    rps integer NULL,
    latency integer NULL,
    error_rate integer NULL
);

CREATE TABLE status_interface
(
    id integer NOT NULL,
    name varchar(50) NULL
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE containers_product ADD CONSTRAINT pk_containers_product
    PRIMARY KEY (id);

CREATE INDEX ixfk_containers_product_product ON containers_product (product_id ASC);

ALTER TABLE interface ADD CONSTRAINT pk_interface
    PRIMARY KEY (id);

CREATE INDEX ixfk_interface_containers_product ON interface (container_id ASC);

CREATE INDEX ixfk_interface_realization_type ON interface (type_id ASC);

CREATE INDEX ixfk_interface_status_interface ON interface (status_id ASC);

ALTER TABLE operation ADD CONSTRAINT pk_operation
    PRIMARY KEY (id);

CREATE INDEX ixfk_operation_method_interface ON operation (interface_id ASC);

ALTER TABLE parameter ADD CONSTRAINT pk_parameter
    PRIMARY KEY (id);

CREATE INDEX ixfk_parameter_method ON parameter (operation_id ASC);

ALTER TABLE realization_type ADD CONSTRAINT pk_realization_type
    PRIMARY KEY (id);

ALTER TABLE sla ADD CONSTRAINT pk_sla
    PRIMARY KEY (id);

CREATE INDEX ixfk_sla_operation ON sla (operation_id ASC);

ALTER TABLE status_interface ADD CONSTRAINT pk_status_interface
    PRIMARY KEY (id);

/* Create Foreign Key Constraints */

ALTER TABLE containers_product ADD CONSTRAINT fk_containers_product_product
    FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE interface ADD CONSTRAINT fk_interface_containers_product
    FOREIGN KEY (container_id) REFERENCES containers_product (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE interface ADD CONSTRAINT fk_interface_realization_type
    FOREIGN KEY (type_id) REFERENCES realization_type (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE interface ADD CONSTRAINT fk_interface_status_interface
    FOREIGN KEY (status_id) REFERENCES status_interface (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE operation ADD CONSTRAINT fk_operation_method_interface
    FOREIGN KEY (interface_id) REFERENCES interface (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE parameter ADD CONSTRAINT fk_parameter_method
    FOREIGN KEY (operation_id) REFERENCES operation (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE sla ADD CONSTRAINT fk_sla_operation
    FOREIGN KEY (operation_id) REFERENCES operation (id) ON DELETE No Action ON UPDATE No Action;
