/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 16-май-2024 10:47:34 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seq_interface_id
;

DROP SEQUENCE IF EXISTS seq_method_id
;

DROP SEQUENCE IF EXISTS seq_paremeter_id
;

DROP SEQUENCE IF EXISTS seq_product_id
;

DROP SEQUENCE IF EXISTS seq_product_interface_id
;

DROP SEQUENCE IF EXISTS seq_tech_product_id
;

DROP SEQUENCE IF EXISTS seq_user_product_id
;

/* Drop Tables */

DROP TABLE IF EXISTS interface CASCADE
;

DROP TABLE IF EXISTS method CASCADE
;

DROP TABLE IF EXISTS parameter CASCADE
;

DROP TABLE IF EXISTS product CASCADE
;

DROP TABLE IF EXISTS product_interface CASCADE
;

DROP TABLE IF EXISTS tech_product CASCADE
;

DROP TABLE IF EXISTS user_product CASCADE
;

/* Create Tables */

CREATE TABLE interface
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_interface_id'::text)::regclass),
    name varchar(150) NULL,
    code varchar(50) NULL,
    link varchar(150) NULL,
    version varchar(50) NULL
)
;

CREATE TABLE method
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_method_id'::text)::regclass),
    interface_id integer NULL,
    name varchar(50) NULL,
    type varchar(50) NULL,
    return_type varchar(100) NULL
)
;

CREATE TABLE parameter
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_paremeter_id'::text)::regclass),
    method_id integer NULL,
    parameter_name varchar(100) NULL,
    parameter_type varchar(50) NULL
)
;

CREATE TABLE product
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_product_id'::text)::regclass),
    name varchar(250) NOT NULL,
    alias varchar(50) NOT NULL
)
;

CREATE TABLE product_interface
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_product_interface_id'::text)::regclass),
    product_id integer NOT NULL,
    interface_id integer NOT NULL
)
;

CREATE TABLE tech_product
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_tech_product_id'::text)::regclass),
    product_id integer NOT NULL,
    tech_id integer NOT NULL
)
;

CREATE TABLE user_product
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_user_product_id'::text)::regclass),
    user_id integer NOT NULL,
    product_id integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE interface ADD CONSTRAINT pk_interface
    PRIMARY KEY (id)
;

ALTER TABLE method ADD CONSTRAINT pk_method
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_method_interface ON method (interface_id ASC)
;

ALTER TABLE parameter ADD CONSTRAINT pk_parameter
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_parameter_method ON parameter (method_id ASC)
;

ALTER TABLE product ADD CONSTRAINT pk_product
    PRIMARY KEY (id)
;

ALTER TABLE product_interface ADD CONSTRAINT pk_product_interface
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_product_interface_interface ON product_interface (interface_id ASC)
;

CREATE INDEX ixfk_product_interface_product ON product_interface (product_id ASC)
;

ALTER TABLE tech_product ADD CONSTRAINT pk_tech_product
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_tech_product_product ON tech_product (product_id ASC)
;

ALTER TABLE user_product ADD CONSTRAINT pk_user_product
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_user_product_product ON user_product (product_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE method ADD CONSTRAINT fk_method_interface
    FOREIGN KEY (interface_id) REFERENCES interface (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE parameter ADD CONSTRAINT fk_parameter_method
    FOREIGN KEY (method_id) REFERENCES method (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_interface ADD CONSTRAINT fk_product_interface_interface
    FOREIGN KEY (interface_id) REFERENCES interface (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_interface ADD CONSTRAINT fk_product_interface_product
    FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tech_product ADD CONSTRAINT fk_tech_product_product
    FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE user_product ADD CONSTRAINT fk_user_product_product
    FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE seq_interface_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_method_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_paremeter_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_product_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_product_interface_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_tech_product_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_user_product_id INCREMENT 1 START 1
;
