ALTER TABLE product.product
    ADD COLUMN source TEXT,
ADD COLUMN upload_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE product.sla ALTER COLUMN rps TYPE NUMERIC(10,5);
ALTER TABLE product.sla ALTER COLUMN latency TYPE NUMERIC(15,5);